spring:
  application:
    name: PasswordManagerFileService
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/password-manager?authSource=admin
---
spring:
  config:
    activate:
      on-profile: pro
  data:
    mongodb:
      uri: ${MONGO.URI}
---