spring:
  application:
    name: PasswordManagerFileService
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/password-manager?authSource=admin
password-manager:
  security:
    jwt:
      secret: caa288691c0e008d66eb44e6c3dc6d5280660ea8cb6d249c449d3750cb54d260
---
spring:
  config:
    activate:
      on-profile: pro
  data:
    mongodb:
      uri: ${MONGO.URI}
password-manager:
  security:
    jwt:
      secret: ${JWT_SECRET}
---